export const PE_COUNTRY_OPTIONS = [
  "United States",
  "United Kingdom",
  "Germany",
  "France",
  "Switzerland",
  "Netherlands",
  "Singapore",
  "United Arab Emirates",
  "Oman",
  "Saudi Arabia",
  "India",
  "China",
  "Japan",
  "Australia",
  "Canada",
  "Brazil",
  "Israel",
  "Kenya",
  "Nigeria",
  "South Africa",
  "Egypt",
] as const;

export const PE_REPORTING_CURRENCIES = ["USD", "EUR", "GBP", "CHF", "SGD", "AED", "OMR", "SAR"] as const;

export const PE_SECTOR_OPTIONS = [
  "FinTech",
  "HealthTech",
  "SaaS",
  "E-Commerce",
  "Climate / CleanTech",
  "AI / ML",
  "Consumer",
  "Enterprise Software",
  "Logistics",
  "EdTech",
  "PropTech",
  "Other",
] as const;
