import type { ModuleName, PermissionLevel, UserRole } from "./types";

export const ROLE_MATRIX: Record<UserRole, Record<ModuleName, PermissionLevel>> = {
  PRINCIPAL: {
    DASHBOARD: "FULL",
    ASSETS: "FULL",
    LANDS: "FULL",
    CARS: "FULL",
    COMPANIES: "FULL",
    DOCUMENTS: "FULL",
    EXPENSES: "FULL",
    REPORTS: "FULL",
    USERS: "FULL",
    AUDIT: "FULL",
  },
  SIGNATORY: {
    DASHBOARD: "FULL",
    ASSETS: "READ",
    LANDS: "READ",
    CARS: "READ",
    COMPANIES: "READ",
    DOCUMENTS: "READ",
    EXPENSES: "NONE",
    REPORTS: "READ",
    USERS: "NONE",
    AUDIT: "NONE",
  },
  FINANCE: {
    DASHBOARD: "READ",
    ASSETS: "READ",
    LANDS: "READ",
    CARS: "READ",
    COMPANIES: "READ",
    DOCUMENTS: "FILTERED",
    EXPENSES: "FULL",
    REPORTS: "FILTERED",
    USERS: "NONE",
    AUDIT: "NONE",
  },
  DIRECTOR: {
    DASHBOARD: "READ",
    ASSETS: "FILTERED",
    LANDS: "FILTERED",
    CARS: "FILTERED",
    COMPANIES: "FILTERED",
    DOCUMENTS: "FILTERED",
    EXPENSES: "NONE",
    REPORTS: "FILTERED",
    USERS: "NONE",
    AUDIT: "NONE",
  },
  EXTERNAL: {
    DASHBOARD: "NONE",
    ASSETS: "NONE",
    LANDS: "NONE",
    CARS: "NONE",
    COMPANIES: "NONE",
    DOCUMENTS: "SHARED_ONLY",
    EXPENSES: "NONE",
    REPORTS: "NONE",
    USERS: "NONE",
    AUDIT: "NONE",
  },
};
