import type { ReportDefinition } from "@/lib/reports/types";

export const REPORT_CATALOG: ReportDefinition[] = [
  {
    id: "net-worth",
    title: "Net Worth Statement",
    description: "Portfolio value, liabilities, and net worth by currency.",
    category: "balance-sheet",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "consolidated-omr",
    title: "Consolidated Net Worth (OMR)",
    description: "Assets and liabilities converted to OMR using latest FX rates.",
    category: "balance-sheet",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "cash-balances",
    title: "Cash & Bank Balances",
    description: "Bank account balances with OMR equivalents and balance dates.",
    category: "balance-sheet",
    requiredModules: ["CASH_MANAGEMENT"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "cash-position",
    title: "Cash Position Report",
    description: "Aggregated cash positions by entity and currency.",
    category: "balance-sheet",
    requiredModules: ["CASH_MANAGEMENT"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "asset-register",
    title: "Asset Register",
    description: "Full list of active and monitored assets with ownership-adjusted values.",
    category: "balance-sheet",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "asset-allocation",
    title: "Asset Allocation",
    description: "Portfolio breakdown by asset category.",
    category: "balance-sheet",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "liabilities",
    title: "Liability & Loan Schedule",
    description: "Active liabilities with outstanding balances and maturity dates.",
    category: "balance-sheet",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "public-equity",
    title: "Public Equity Holdings",
    description: "Listed equity positions across imported broker reports.",
    category: "portfolio",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "pe-portfolio",
    title: "PE / VC Portfolio Summary",
    description: "Private equity companies with invested capital, fair value, and distributions.",
    category: "portfolio",
    requiredModules: ["PRIVATE_EQUITY"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "lp-fund-portfolio",
    title: "Fund LP Portfolio Summary",
    description: "LP fund commitments with paid-in capital, NAV, multiples, and unfunded balances.",
    category: "portfolio",
    requiredModules: ["FUND_LP"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "dividend-distribution-income",
    title: "Dividend & Distribution Income",
    description: "Private equity and fund LP distributions for the selected period.",
    category: "portfolio",
    requiredModules: [],
    requiredModulesAny: ["PRIVATE_EQUITY", "FUND_LP"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "total-portfolio-income",
    title: "Total Portfolio Income",
    description: "Combined rental and investment income for the selected period.",
    category: "portfolio",
    requiredModules: [],
    requiredModulesAny: ["REAL_ESTATE", "PRIVATE_EQUITY", "FUND_LP"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "portfolio-performance",
    title: "Portfolio Performance Report",
    description: "Valuation-based portfolio returns and per-asset month-to-date performance.",
    category: "portfolio",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "cheques",
    title: "Cheque Register",
    description: "Pending and deposited cheques with due dates and amounts.",
    category: "operations",
    requiredModules: ["CHEQUES"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "expenses",
    title: "Expense Summary",
    description: "Expenses by category and status for the selected period.",
    category: "operations",
    requiredModules: ["EXPENSES"],
    supportsEntityFilter: false,
    supportsDateRange: true,
  },
  {
    id: "exits",
    title: "Realized Exits",
    description: "Asset, real estate, and private equity exits with proceeds, realized gains, and ROI.",
    category: "operations",
    requiredModules: [],
    requiredModulesAny: ["ASSETS", "REAL_ESTATE", "PRIVATE_EQUITY"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "exit-analytics",
    title: "Exit Analytics",
    description: "Summary metrics for realized exits: total gain, average ROI, win rate, and category breakdown.",
    category: "portfolio",
    requiredModules: [],
    requiredModulesAny: ["ASSETS", "REAL_ESTATE", "PRIVATE_EQUITY"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "lands",
    title: "Land Portfolio",
    description: "Land parcels with location, area, and values.",
    category: "registers",
    requiredModules: ["LANDS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "vehicles",
    title: "Vehicle Fleet",
    description: "Registered vehicles with registration and insurance expiry dates.",
    category: "registers",
    requiredModules: ["CARS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "companies",
    title: "Registered Companies",
    description: "Corporate entities with registration details and expiry dates.",
    category: "registers",
    requiredModules: ["COMPANIES"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "document-expiry",
    title: "Document Expiry",
    description: "Documents expiring soon or already expired.",
    category: "registers",
    requiredModules: ["DOCUMENTS"],
    supportsEntityFilter: false,
    supportsDateRange: false,
  },
  {
    id: "insurance-register",
    title: "Insurance Register",
    description: "Insurance policies with premiums, expiry dates, and linked assets.",
    category: "registers",
    requiredModules: ["INSURANCE"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "family-register",
    title: "Family Register",
    description: "Family members with KYC status, beneficiary flags, and ownership stake counts.",
    category: "registers",
    requiredModules: ["FAMILY_MEMBERS"],
    supportsEntityFilter: false,
    supportsDateRange: false,
  },
  {
    id: "succession-status",
    title: "Succession Plan Status",
    description: "Estate plans with review dates, checklist completion, and missing legal documents.",
    category: "registers",
    requiredModules: ["SUCCESSION"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "contacts-directory",
    title: "Contacts Directory",
    description: "External contacts with follow-up dates, organizations, and entity assignments.",
    category: "registers",
    requiredModules: ["CONTACTS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "bank-accounts",
    title: "Bank Accounts",
    description: "Registered bank accounts across entities.",
    category: "registers",
    requiredModules: [],
    requiredModulesAny: ["ASSETS", "CASH_MANAGEMENT"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "proposals",
    title: "Investment Proposal Pipeline",
    description: "Investment proposals by status and amount.",
    category: "registers",
    requiredModules: ["PROPOSALS"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "re-portfolio",
    title: "Property Portfolio",
    description: "Real estate properties with occupancy, rent, and valuation metrics.",
    category: "real-estate",
    requiredModules: ["REAL_ESTATE"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "rental-income",
    title: "Rental Income Report",
    description: "Collected rental income for the selected period.",
    category: "real-estate",
    requiredModules: ["REAL_ESTATE"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "re-rent-register",
    title: "Rent Collection Register",
    description: "Rent schedule entries with payment status and PDC tracking.",
    category: "real-estate",
    requiredModules: ["REAL_ESTATE"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "re-leases",
    title: "Active Lease Register",
    description: "Active and pending leases with rent terms and expiry dates.",
    category: "real-estate",
    requiredModules: ["REAL_ESTATE"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "re-expenses",
    title: "Property Expense Summary",
    description: "Operating expenses by property and category for the selected period.",
    category: "real-estate",
    requiredModules: ["REAL_ESTATE"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "re-valuation-history",
    title: "Property Valuation History",
    description: "Historical property valuations over time.",
    category: "real-estate",
    requiredModules: ["REAL_ESTATE"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "valuation-history",
    title: "Valuation History",
    description: "Historical asset valuations over time.",
    category: "advanced",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
];

export const REPORT_CATEGORY_LABELS: Record<string, string> = {
  "balance-sheet": "Balance Sheet",
  portfolio: "Portfolio",
  operations: "Operations",
  registers: "Registers",
  "real-estate": "Real Estate",
  advanced: "Advanced",
};

export function getReportDefinition(reportId: string): ReportDefinition | undefined {
  return REPORT_CATALOG.find((report) => report.id === reportId);
}
