import type { ReportDefinition } from "@/lib/reports/types";

export const REPORT_CATALOG: ReportDefinition[] = [
  {
    id: "net-worth",
    title: "Net Worth Statement",
    description: "Portfolio value, liabilities, and net worth by currency.",
    category: "balance-sheet",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "consolidated-omr",
    title: "Consolidated Net Worth (OMR)",
    description: "Assets and liabilities converted to OMR using latest FX rates.",
    category: "balance-sheet",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "asset-register",
    title: "Asset Register",
    description: "Full list of active and monitored assets with ownership-adjusted values.",
    category: "balance-sheet",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "asset-allocation",
    title: "Asset Allocation",
    description: "Portfolio breakdown by asset category.",
    category: "balance-sheet",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "liabilities",
    title: "Liability & Loan Schedule",
    description: "Active liabilities with outstanding balances and maturity dates.",
    category: "balance-sheet",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "public-equity",
    title: "Public Equity Holdings",
    description: "Listed equity positions across imported broker reports.",
    category: "portfolio",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "pe-portfolio",
    title: "PE / VC Portfolio Summary",
    description: "Private equity companies with invested capital, fair value, and distributions.",
    category: "portfolio",
    requiredModules: ["PRIVATE_EQUITY"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "lp-fund-portfolio",
    title: "Fund LP Portfolio Summary",
    description: "LP fund commitments with paid-in capital, NAV, multiples, and unfunded balances.",
    category: "portfolio",
    requiredModules: ["FUND_LP"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "cheques",
    title: "Cheque Register",
    description: "Pending and deposited cheques with due dates and amounts.",
    category: "operations",
    requiredModules: ["CHEQUES"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "expenses",
    title: "Expense Summary",
    description: "Expenses by category and status for the selected period.",
    category: "operations",
    requiredModules: ["EXPENSES"],
    supportsEntityFilter: false,
    supportsDateRange: true,
  },
  {
    id: "exits",
    title: "Realized Exits",
    description: "Asset exits with proceeds and realized gains.",
    category: "operations",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "lands",
    title: "Land Portfolio",
    description: "Land parcels with location, area, and values.",
    category: "registers",
    requiredModules: ["LANDS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "vehicles",
    title: "Vehicle Fleet",
    description: "Registered vehicles with registration and insurance expiry dates.",
    category: "registers",
    requiredModules: ["CARS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "companies",
    title: "Registered Companies",
    description: "Corporate entities with registration details and expiry dates.",
    category: "registers",
    requiredModules: ["COMPANIES"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "document-expiry",
    title: "Document Expiry",
    description: "Documents expiring soon or already expired.",
    category: "registers",
    requiredModules: ["DOCUMENTS"],
    supportsEntityFilter: false,
    supportsDateRange: false,
  },
  {
    id: "insurance-register",
    title: "Insurance Register",
    description: "Insurance policies with premiums, expiry dates, and linked assets.",
    category: "registers",
    requiredModules: ["INSURANCE"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "bank-accounts",
    title: "Bank Accounts",
    description: "Registered bank accounts across entities.",
    category: "registers",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "proposals",
    title: "Investment Proposal Pipeline",
    description: "Investment proposals by status and amount.",
    category: "registers",
    requiredModules: ["PROPOSALS"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "re-portfolio",
    title: "Property Portfolio",
    description: "Real estate properties with occupancy, rent, and valuation metrics.",
    category: "real-estate",
    requiredModules: ["REAL_ESTATE"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "re-rent-register",
    title: "Rent Collection Register",
    description: "Rent schedule entries with payment status and PDC tracking.",
    category: "real-estate",
    requiredModules: ["REAL_ESTATE"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "re-leases",
    title: "Active Lease Register",
    description: "Active and pending leases with rent terms and expiry dates.",
    category: "real-estate",
    requiredModules: ["REAL_ESTATE"],
    supportsEntityFilter: true,
    supportsDateRange: false,
  },
  {
    id: "re-expenses",
    title: "Property Expense Summary",
    description: "Operating expenses by property and category for the selected period.",
    category: "real-estate",
    requiredModules: ["REAL_ESTATE"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "re-valuation-history",
    title: "Property Valuation History",
    description: "Historical property valuations over time.",
    category: "real-estate",
    requiredModules: ["REAL_ESTATE"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
  {
    id: "valuation-history",
    title: "Valuation History",
    description: "Historical asset valuations over time.",
    category: "advanced",
    requiredModules: ["ASSETS"],
    supportsEntityFilter: true,
    supportsDateRange: true,
  },
];

export const REPORT_CATEGORY_LABELS: Record<string, string> = {
  "balance-sheet": "Balance Sheet",
  portfolio: "Portfolio",
  operations: "Operations",
  registers: "Registers",
  "real-estate": "Real Estate",
  advanced: "Advanced",
};

export function getReportDefinition(reportId: string): ReportDefinition | undefined {
  return REPORT_CATALOG.find((report) => report.id === reportId);
}
